package thethongminh;

import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {

    private TheThongMinh host;
    private JFrame frame;
    static byte counter;
    static boolean ts_du = false;
    static Customer customer;
    private boolean input = false;

    public NewJFrame() {
        initComponents();
        customer = new Customer();
        host = new TheThongMinh();
    }

    //hien thi apdu lenh len GUI
    public void setTheCommandAPDUOnGUI(byte[] cmnds, byte[] data, byte lc, byte le) {
        text_cla.setText(host.atrToHex(cmnds[0]));
        text_ins.setText(host.atrToHex(cmnds[1]));
        text_p1.setText(host.atrToHex(cmnds[2]));
        text_p2.setText(host.atrToHex(cmnds[3]));
        text_lc.setText(host.atrToHex(lc));
        //data
        String temp = "";
        for (int i = 0; i < data.length; i++) {
            temp += host.atrToHex(data[i]);
            temp += " ";
        }
        text_data_cmd.setText(temp);
        text_le.setText(host.atrToHex(le));
    }

    public void setTheCommandAPDUOnGUI2(byte[] cmnds, byte[] data, short lc, short le) {
        text_cla.setText(host.atrToHex(cmnds[0]));
        text_ins.setText(host.atrToHex(cmnds[1]));
        text_p1.setText(host.atrToHex(cmnds[2]));
        text_p2.setText(host.atrToHex(cmnds[3]));
        text_lc.setText(host.shorttoHex(lc));
        //data
        String temp = "";
        for (int i = 0; i < data.length; i++) {
            temp += host.atrToHex(data[i]);
            temp += " ";
        }
        text_data_cmd.setText(temp);
        text_le.setText(host.shorttoHex(le));
    }

    //hien thi apdu phan hoi len GUI
    public void setTheResponseAPDUOnGUI(short le) {
        byte[] status = host.decodeStatus();//sw1 sw2
        text_sw1.setText(String.valueOf(host.atrToHex(status[0])));
        text_sw2.setText(String.valueOf(host.atrToHex(status[1])));
        byte[] dataOut = host.decodeDataOut();
        if (le != 0 && dataOut.length != 0) {
            //hien thi du lieu ra
            String temp = "";
            for (int i = 0; i < dataOut.length; i++) {
                temp += host.atrToHex(dataOut[i]);
                temp += " ";
            }
            text_data_rs.setText(temp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        text_cla = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_ins = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_p1 = new javax.swing.JTextField();
        text_p2 = new javax.swing.JTextField();
        text_lc = new javax.swing.JTextField();
        text_le = new javax.swing.JTextField();
        text_data_cmd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        button_connect = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        text_data_rs = new javax.swing.JTextField();
        text_sw1 = new javax.swing.JTextField();
        text_sw2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        button_close = new javax.swing.JButton();
        text_connect = new javax.swing.JTextField();
        text_close = new javax.swing.JTextField();
        button_unclock = new javax.swing.JButton();
        button_init = new javax.swing.JButton();
        button_clear = new javax.swing.JButton();
        button_sendto_applet = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button_update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        text_hoten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        text_ns = new javax.swing.JTextField();
        text_qq = new javax.swing.JTextField();
        text_gt = new javax.swing.JTextField();
        button_enter = new javax.swing.JButton();
        text_pin = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APDU Process", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setName(""); // NOI18N

        text_cla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_cla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_claActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CLA");

        text_ins.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_insActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("INS");

        text_p1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_p1ActionPerformed(evt);
            }
        });

        text_p2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        text_lc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        text_le.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_le.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_leActionPerformed(evt);
            }
        });

        text_data_cmd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_data_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_data_cmdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("P1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("P2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("LC");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Data: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("LE");

        button_connect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_connect.setText("Establish Connection with CardReader Simulator");
        button_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_connectActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Response APDU");

        text_data_rs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        text_sw1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_sw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_sw1ActionPerformed(evt);
            }
        });

        text_sw2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_sw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_sw2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("SW2");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("SW1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Data: ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Command APDU");

        button_close.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_close.setText("Close the Connection with CardReader Simulator");
        button_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_closeActionPerformed(evt);
            }
        });

        text_connect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_connectActionPerformed(evt);
            }
        });

        text_close.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        button_unclock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_unclock.setText("Unblock Card");
        button_unclock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_unclockActionPerformed(evt);
            }
        });

        button_init.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_init.setText("Init Card");
        button_init.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_initActionPerformed(evt);
            }
        });

        button_clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_clear.setText("Clear Card");
        button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearActionPerformed(evt);
            }
        });

        button_sendto_applet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_sendto_applet.setText("Send to Applet");
        button_sendto_applet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sendto_appletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(text_le, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text_data_cmd))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(button_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(77, 77, 77)
                                                    .addComponent(text_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(text_close, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(button_unclock)
                                        .addGap(55, 55, 55)
                                        .addComponent(button_init, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(button_sendto_applet)
                                        .addGap(46, 46, 46)
                                        .addComponent(button_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_sw1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(text_sw2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(text_cla, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(text_lc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text_data_rs, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_cla, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_lc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_le, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(text_data_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_sw1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_sw2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_data_rs, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(29, 29, 29)
                        .addComponent(button_unclock, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_sendto_applet, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_init, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PIN: ");

        button_update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_update.setText("Cập Nhật");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Họ và Tên: ");

        text_hoten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Giới Tính: ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Ngày Sinh: ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Quê Quán: ");

        text_ns.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        text_qq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_qq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_qqActionPerformed(evt);
            }
        });

        text_gt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        button_enter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_enter.setText("Enter");
        button_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_enterActionPerformed(evt);
            }
        });

        text_pin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Ảnh đại diện:");

        jLabel19.setText("Ảnh đại diện");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_ns, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(button_update, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_qq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(text_gt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_ns, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_qq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_update, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_claActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_claActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_claActionPerformed

    private void text_insActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_insActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_insActionPerformed

    private void text_p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_p1ActionPerformed

    private void text_leActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_leActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_leActionPerformed

    private void text_data_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_data_cmdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_data_cmdActionPerformed

    private void button_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_connectActionPerformed
        byte datalen = 6; //do dai du lieu gui vao applet, RID,PIX 
        byte maxdata_expect = 0;//du lieu nhan mong doi (Le)
        counter = 3;
        host.establishConnectionToSimulator();//thiet lap ket noi
        host.pwrUp();//cung cap dien
        byte[] cmd = {(byte) 0x00, (byte) 0xA4, (byte) 0x04, (byte) 0x00};// select
        host.setTheAPDUCommands(cmd);//set APDU header
        host.setTheDataLength(datalen);//LC
        //mang data gui di la RID,PIX
        byte[] data = {(byte) 0x5F, (byte) 0x33, (byte) 0xE8, (byte) 0x2C, (byte) 0xDF, (byte) 0x21};
        host.setTheDataIn(data);//gui du lieu toi applet
        host.setExpctdByteLength(maxdata_expect);//LE
        setTheCommandAPDUOnGUI(cmd, data, datalen, maxdata_expect);//hien thi apdu cmd len GUI
        host.exchangeTheAPDUWithSimulator();//nhan du lieu phan hoi
        host.decodeStatus();//sw1 sw2
        setTheResponseAPDUOnGUI(maxdata_expect);//hien thi du lieu phan hoi tu applet len GUI
        text_connect.setText("Done");
        text_close.setText("");
    }//GEN-LAST:event_button_connectActionPerformed

    private void text_sw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_sw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_sw1ActionPerformed

    private void text_sw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_sw2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_sw2ActionPerformed

    private void button_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_closeActionPerformed
        // TODO add your handling code here:
        host.pwrDown();
        host.closeConnection();
        text_hoten.setText("");
        text_ns.setText("");
        text_qq.setText("");
        text_gt.setText("");
        text_connect.setText("");
        text_close.setText("Done");
        text_data_rs.setText("");
        text_sw1.setText("");
        text_sw2.setText("");
        text_data_cmd.setText("");
        text_cla.setText("");
        text_ins.setText("");
        text_p1.setText("");
        text_p2.setText("");
        text_lc.setText("");
        text_le.setText("");
        text_pin.setText("");
    }//GEN-LAST:event_button_closeActionPerformed

    private void text_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_connectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_connectActionPerformed

    private void button_unclockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_unclockActionPerformed
        short datalen = 1; //do dai du lieu gui vao applet
        short maxdata_expect = 0;//du lieu nhan mong doi (Le)
        byte[] cmd = {(byte) 0x00, (byte) 0x11, (byte) 0x00, (byte) 0x00};
        host.setTheAPDUCommands(cmd);//set APDU header
        host.setTheDataLengthShort(datalen);//LC
        //mang data gui di la RID,PIX
        byte[] data_u = {(byte) 0};
        host.setTheDataIn(data_u);
        //host.setExpctdByteLength(maxdata_expect);//LE
        host.setExpctShortLength(maxdata_expect);
        setTheCommandAPDUOnGUI2(cmd, data_u, datalen, maxdata_expect);//hien thi apdu cmd len GUI
        host.exchangeTheAPDUWithSimulator();//nhan du lieu phan hoi
        host.decodeStatus();//sw1 sw2
        setTheResponseAPDUOnGUI(maxdata_expect);//hien thi du lieu phan hoi tu applet len GUI
        host.decodeStatus();//sw1 sw2
        setTheResponseAPDUOnGUI(maxdata_expect);//hien thi du lieu phan hoi tu applet len GUI
        JOptionPane.showMessageDialog(null, "Thẻ đã được mở khóa.");
    }//GEN-LAST:event_button_unclockActionPerformed

    private void button_initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_initActionPerformed
        // TODO add your handling code here:
        if (input == false) {
            Form_KhoiTao fkt = new Form_KhoiTao();
            fkt.setVisible(true);
            fkt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_button_initActionPerformed

    private void button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearActionPerformed
        input = false;
        counter = 3;
        short datalen = 1; //do dai du lieu gui vao applet
        short maxdata_expect = 0;//du lieu nhan mong doi (Le)
        byte[] cmd = {(byte) 0x00, (byte) 0x19, (byte) 0x00, (byte) 0x00};
        host.setTheAPDUCommands(cmd);//set APDU header
        host.setTheDataLengthShort(datalen);//LC
        byte[] data_u = {(byte) 0};
        host.setTheDataIn(data_u);
        host.setExpctShortLength(maxdata_expect);
        setTheCommandAPDUOnGUI2(cmd, data_u, datalen, maxdata_expect);//hien thi apdu cmd len GUI
        host.exchangeTheAPDUWithSimulator();//nhan du lieu phan hoi
        host.decodeStatus();//sw1 sw2
        setTheResponseAPDUOnGUI(maxdata_expect);//hien thi du lieu phan hoi tu applet len GUI
        host.decodeStatus();//sw1 sw2
        setTheResponseAPDUOnGUI(maxdata_expect);//hien thi du lieu phan hoi tu applet len GUI
        text_hoten.setText("");
        text_ns.setText("");
        text_qq.setText("");
        text_gt.setText("");
        text_pin.setText("");
        JOptionPane.showMessageDialog(null, "Thẻ đã xóa dữ liệu.");
    }//GEN-LAST:event_button_clearActionPerformed

    private void button_sendto_appletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sendto_appletActionPerformed
        if (input == false) {
            //chuyen du lieu xuong applet
            String hoten = customer.getName();
            String ngaysinh = customer.getBirthDate();
            String quequan = customer.getAddress();
            String pin = customer.getPin();
//            Double balance = customer.getBalance();
            String gioitinh = customer.getGender();

//            String arrsendapplet = hoten.concat(".").concat(ngaysinh).concat(".").concat(quequan).concat(".").concat(gioitinh).concat(".").concat(balance.toString()).concat(".").concat(pin);
            String arrsendapplet = hoten.concat(".").concat(ngaysinh).concat(".").concat(quequan).concat(".").concat(gioitinh).concat(".").concat(pin);

            //JOptionPane.showMessageDialog(null, pin);
            int len = arrsendapplet.length();
            byte datalen = (byte) len; //do dai du lieu gui vao applet
            byte maxdata_expect = 127;//du lieu nhan mong doi (Le)
            byte[] cmd = {(byte) 0x00, (byte) 0x10, (byte) 0x00, (byte) 0x00};
            host.setTheAPDUCommands(cmd);//set APDU header
            host.setTheDataLength(datalen);//LC
            //mang data gui di la RID,PIX
            byte[] data = arrsendapplet.getBytes();
            host.setTheDataIn(data);//gui du lieu toi applet
            host.setExpctdByteLength(maxdata_expect);//LE
            setTheCommandAPDUOnGUI(cmd, data, datalen, maxdata_expect);//hien thi apdu cmd len GUI
            host.exchangeTheAPDUWithSimulator();//nhan du lieu phan hoi
            host.decodeStatus();//sw1 sw2
            setTheResponseAPDUOnGUI(maxdata_expect);//hien thi du lieu phan hoi tu applet len GUI
            byte[] dataOut = host.decodeDataOut();//du lieu nhan ve tu applet
            String out = new String(dataOut);
            
            sendAvatarToApplet();
            
            String[] aaa = out.split(":");
            String ht1 = aaa[0];
            String ht2 = aaa[1];
            String ht3 = aaa[2];
            String ht4 = aaa[3];
            text_hoten.setText(ht1);
            text_ns.setText(ht2);
            text_qq.setText(ht3);
            text_gt.setText(ht4);
            input = true;
        } else {
            JOptionPane.showMessageDialog(null, "Card already has data.");
        }
    }//GEN-LAST:event_button_sendto_appletActionPerformed

    private void sendAvatarToApplet() {
        byte[] avatar = customer.getAvatar();

        int len = avatar.length;
        byte datalen = (byte) len;
        byte maxdata_expect = 127;
        byte[] cmd = {(byte) 0x00, (byte) 0x21, (byte) 0x00, (byte) 0x00};
        host.setTheAPDUCommands(cmd);
        host.setTheDataLength(datalen);
        host.setTheDataIn(avatar);
        host.setExpctdByteLength(datalen);
//        setTheCommandAPDUOnGUI(cmd, avatar, datalen, maxdata_expect);
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();
//        setTheResponseAPDUOnGUI(maxdata_expect);
        byte[] dataOut = host.decodeDataOut();
        String out = new String(dataOut);
        System.out.println("avatar" + out);
    }

    private void button_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_enterActionPerformed
        // TODO add your handling code here:
        if (checkcard() == false) {
            if (checkpin() == true) {
                get_info_customer();
            } else {
                JOptionPane.showMessageDialog(null, "Mã PIN sai. Vui lòng nhập lại.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Thẻ của bạn đã bị khóa. Tìm cách mở khóa đi.");
        }
    }//GEN-LAST:event_button_enterActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:
//        set_balance();
//        set_point();
    }//GEN-LAST:event_button_updateActionPerformed

    private void text_qqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_qqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_qqActionPerformed
    private void get_info_customer() {
        short datalen = 1; //do dai du lieu gui vao applet
        short maxdata_expect = 200;//du lieu nhan mong doi (Le)
        byte[] cmd = {(byte) 0x00, (byte) 0x13, (byte) 0x00, (byte) 0x00};
        host.setTheAPDUCommands(cmd);//set APDU header
        host.setTheDataLengthShort(datalen);//LC
        //mang data gui di la RID,PIX
        byte[] data_u = {(byte) 0};
        host.setTheDataIn(data_u);
        //host.setExpctdByteLength(maxdata_expect);//LE
        host.setExpctShortLength(maxdata_expect);
        setTheCommandAPDUOnGUI2(cmd, data_u, datalen, maxdata_expect);//hien thi apdu cmd len GUI
        host.exchangeTheAPDUWithSimulator();//nhan du lieu phan hoi
        host.decodeStatus();//sw1 sw2
        setTheResponseAPDUOnGUI(maxdata_expect);//hien thi du lieu phan hoi tu applet len GUI
        host.decodeStatus();//sw1 sw2
        setTheResponseAPDUOnGUI(maxdata_expect);//hien thi du lieu phan hoi tu applet len GUI
        byte[] dataOut = host.decodeDataOut();//du lieu nhan ve tu applet
        String out = new String(dataOut);
        String[] aaa = out.split(":");
        String ht1 = aaa[0];
        String ht2 = aaa[1];
        String ht3 = aaa[2];
        String ht4 = aaa[3];

        text_hoten.setText(ht1);
        text_ns.setText(ht2);
        text_qq.setText(ht3);
        text_gt.setText(ht4);
    }

    private void get_balance() {

    }

    private void get_point() {

    }

    private void set_balance() {

    }

    private void set_point() {

    }

    //check xem thẻ bị khóa hay chưa (OK)
    private boolean checkcard() {
        short datalen = 1; //do dai du lieu gui vao applet
        short maxdata_expect = 1;//du lieu nhan mong doi (Le)
        byte[] cmd = {(byte) 0x80, (byte) 0x18, (byte) 0x00, (byte) 0x00};
        host.setTheAPDUCommands(cmd);
        host.setTheDataLengthShort(datalen);
        byte[] data_u = {(byte) 0};
        host.setTheDataIn(data_u);
        host.setExpctShortLength(maxdata_expect);
        setTheCommandAPDUOnGUI2(cmd, data_u, datalen, maxdata_expect);
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();
        setTheResponseAPDUOnGUI(maxdata_expect);
        byte[] dataOut = host.decodeDataOut();//du lieu nhan ve tu applet
        if (dataOut[0] == (byte) 0x00) {//chưa bị khóa, Ok
            return false;
        } else {
            return true;
        }
    }

    //gửi mã PIN vào applet để applet check (OK)
    private boolean checkpin() {
        String pin = Arrays.toString(text_pin.getPassword());
        short datalen = (short) pin.length(); //do dai du lieu gui vao applet
        short maxdata_expect = 1;//du lieu nhan mong doi (Le)
        byte[] cmd = {(byte) 0x00, (byte) 0x20, (byte) 0x00, (byte) 0x00};
        host.setTheAPDUCommands(cmd);
        host.setTheDataLengthShort(datalen);
        byte[] data_u = pin.getBytes();
        host.setTheDataIn(data_u);
        host.setExpctShortLength(maxdata_expect);
        setTheCommandAPDUOnGUI2(cmd, data_u, datalen, maxdata_expect);
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();
        setTheResponseAPDUOnGUI(maxdata_expect);
        byte[] dataOut = host.decodeDataOut();//du lieu nhan ve tu applet
        if (dataOut[0] == (byte) 0x00) {//đúng mã PIN
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_close;
    private javax.swing.JButton button_connect;
    private javax.swing.JButton button_enter;
    private javax.swing.JButton button_init;
    private javax.swing.JButton button_sendto_applet;
    private javax.swing.JButton button_unclock;
    private javax.swing.JButton button_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_cla;
    private javax.swing.JTextField text_close;
    private javax.swing.JTextField text_connect;
    private javax.swing.JTextField text_data_cmd;
    private javax.swing.JTextField text_data_rs;
    private javax.swing.JTextField text_gt;
    private javax.swing.JTextField text_hoten;
    private javax.swing.JTextField text_ins;
    private javax.swing.JTextField text_lc;
    private javax.swing.JTextField text_le;
    private javax.swing.JTextField text_ns;
    private javax.swing.JTextField text_p1;
    private javax.swing.JTextField text_p2;
    private javax.swing.JPasswordField text_pin;
    private javax.swing.JTextField text_qq;
    private javax.swing.JTextField text_sw1;
    private javax.swing.JTextField text_sw2;
    // End of variables declaration//GEN-END:variables
}
